seed = 0
parent_dir = "exp/poly_lines/"
real_data_path = "data/poly_lines/"
model_type = "mlp"
num_numerical_features = 2
device = "cpu"

[model_params]
d_in = 2
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    256,
    1024,
    1024,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 3000
lr = 0.001
weight_decay = 0.0
batch_size = 512

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 2048
batch_size = 512
seed = 0